# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'News' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'HandyJSON', '~> 5.0.4-beta'
  pod 'Kingfisher', '~> 7.1.2'
  pod 'IBAnimatable'
  pod 'SwiftTheme'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SQLite.swift'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'SGPagingView'
  pod 'BMPlayer'
  pod 'FDFullscreenPopGesture'
  pod 'NVActivityIndicatorView'
  pod 'lottie-ios'
  
end
